# Generated by Django 4.2.6 on 2023-10-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='rayorpay_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
